import {db,auth,origin,owner,uid,now,text,integer,date,option,hashPin,eq,auditStmt,permissionsList,channels,json,fail,APIError} from '@/db/store';
import {createTransaction,deliver} from '@/db/transactions';
export async function POST(req:Request){try{origin(req);const u=await auth(req);const b:any=await req.json();const q=db();if(b.action==='transaction'){const id=await createTransaction(u,b);return json({ok:true,id})}owner(u);const ts=now();
if(b.action==='player'){const id=text(b.id||('DC-'+uid().slice(0,8)),'Player ID',80);const name=text(b.name,'Nama',80),rank=text(b.rank,'Rank',50),status=option(b.status,['Active','Inactive']),join=date(b.join_date);await q.batch([q.prepare('INSERT INTO players(id,name,rank,status,join_date,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,rank=excluded.rank,status=excluded.status,join_date=excluded.join_date,notes=excluded.notes,updated_at=excluded.created_at').bind(id,name,rank,status,join,String(b.notes||'').slice(0,1000),u.id,ts),auditStmt(u,'player',id+' '+name)]);}
else if(b.action==='item'){const id=b.id?text(b.id,'Item ID',80):uid();await q.batch([q.prepare('INSERT INTO items(id,name,category,minimum,unit,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,category=excluded.category,minimum=excluded.minimum,unit=excluded.unit,notes=excluded.notes,updated_at=excluded.created_at').bind(id,text(b.name,'Nama',80),text(b.category,'Kategori',60),integer(b.minimum,'Minimum',true),text(b.unit,'Unit',20),String(b.notes||'').slice(0,1000),u.id,ts),auditStmt(u,'item',id)]);}
else if(b.action==='target'){const player=text(b.player_id,'Player',80),month=text(b.month,'Bulan',7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw new APIError('Bulan tidak valid.');await q.batch([q.prepare('INSERT INTO setoran_targets(id,player_id,month,amount,created_at,created_by) VALUES(?,?,?,?,?,?) ON CONFLICT(player_id,month) DO UPDATE SET amount=excluded.amount,created_at=excluded.created_at,created_by=excluded.created_by').bind(uid(),player,month,integer(b.amount,'Target',true),ts,u.id),auditStmt(u,'target',player+' '+month)]);}
else if(b.action==='access'){const id=b.id?text(b.id,'Access ID',80):uid();if(id===u.id&&(b.active===false||b.role_id!=='owner'))throw new APIError('Akses Owner yang sedang digunakan tidak dapat dinonaktifkan atau diturunkan.');const previous=await q.prepare('SELECT * FROM users WHERE id=?').bind(id).first<any>();const role=option(b.role_id,['owner','member']);let hash=previous?.pin_hash,salt=previous?.salt;if(b.pin){const pin=text(b.pin,'PIN',4);if(!/^\d{4}$/.test(pin))throw new APIError('PIN harus 4 angka.');const all=await q.prepare('SELECT * FROM users WHERE id!=?').bind(id).all<any>();if(!previous&&all.results.length>=30)throw new APIError('Maksimal 30 profil akses.');for(const other of all.results)if(eq(await hashPin(pin,other.salt),other.pin_hash))throw new APIError('PIN sudah digunakan profil lain.');salt=uid();hash=await hashPin(pin,salt);}if(!hash)throw new APIError('Masukkan PIN baru.');await q.batch([q.prepare('INSERT INTO users(id,name,role_id,pin_hash,salt,active,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role_id=excluded.role_id,pin_hash=excluded.pin_hash,salt=excluded.salt,active=excluded.active').bind(id,text(b.name,'Nama profil',80),role,hash,salt,b.active===false?0:1,ts),q.prepare('DELETE FROM sessions WHERE user_id=?').bind(id),auditStmt(u,'access','Profil akses diperbarui: '+id)]);}
else if(b.action==='permissions'){const stmts=permissionsList.map(key=>q.prepare('INSERT INTO permissions(id,role_id,key,enabled) VALUES(?,?,?,?) ON CONFLICT(role_id,key) DO UPDATE SET enabled=excluded.enabled').bind('member-'+key,'member',key,b.permissions?.includes(key)?1:0));await q.batch([...stmts,auditStmt(u,'permissions','Member permissions diperbarui')]);}
else if(b.action==='discord'){const ch=option(b.channel,Object.keys(channels));await q.batch([q.prepare('UPDATE discord_settings SET enabled=? WHERE channel=?').bind(b.enabled?1:0,ch),auditStmt(u,'discord',ch+' '+!!b.enabled)]);}
else if(b.action==='retry'){await deliver();}
else throw new APIError('Aksi tidak dikenal.');return json({ok:true});}catch(e){return fail(e)}}
