import {db,uid,now,today,text,integer,date,option,permit,owner,APIError,channels,runtime} from './store';
export async function createTransaction(u:any,b:any){const type=option(b.type,['Deposit','Inventory In','Inventory Out','Income','Expense','Correction']);if(type==='Deposit')permit(u,'deposit.write');else if(type.startsWith('Inventory'))permit(u,'inventory.write');else owner(u);const request=text(b.request_id,'Request ID',80);const existing=await db().prepare('SELECT id,created_by FROM transaction_logs WHERE request_id=?').bind(request).first<any>();if(existing){if(existing.created_by!==u.id)throw new APIError('Request ID tidak valid.');return existing.id;}
let player:string|null=null,item:string|null=null,amount=0,quantity=0,original:any=null;let category=text(b.category||type,'Kategori',60),description=text(b.description||category,'Keterangan',500);const operator=text(b.operator,'Dicatat / diterima oleh',80);const notes=typeof b.notes==='string'?b.notes.slice(0,1000):'';const day=date(b.date||today());let proof:string|null=null;
if(type==='Correction'){const oid=integer(b.original_id,'Transaksi');original=await db().prepare("SELECT * FROM transaction_logs WHERE id=? AND type!='Correction'").bind(oid).first<any>();if(!original)throw new APIError('Transaksi tidak ditemukan.');if(await db().prepare('SELECT id FROM transaction_logs WHERE reversal_of=?').bind(oid).first())throw new APIError('Transaksi sudah dikoreksi.');amount=-original.amount;quantity=-original.quantity;player=original.player_id;item=original.item_id;category=original.category;description='Reversal TRX-'+String(oid).padStart(6,'0')+': '+text(b.description,'Alasan koreksi');}
else {if(type==='Deposit'){player=text(b.player_id,'Player',80);const p=await db().prepare("SELECT id FROM players WHERE id=? AND status='Active'").bind(player).first();if(!p)throw new APIError('Pilih player aktif.');category=option(b.category,['Weekly','Monthly','Special','Other']);const mode=option(b.deposit_kind||'money',['money','item']);if(mode==='item'){item=text(b.item_id,'Item',80);quantity=integer(b.quantity,'Jumlah item');}else amount=integer(b.amount,'Jumlah uang');}
if(type==='Income'||type==='Expense'){amount=integer(b.amount,'Jumlah')*(type==='Expense'?-1:1);category=option(b.category,type==='Expense'?['Operational','Equipment','Salary','Bonus','Other']:['Other Income']);}
if(type.startsWith('Inventory')){item=text(b.item_id,'Item',80);quantity=integer(b.quantity,'Jumlah')*(type==='Inventory Out'?-1:1);if(b.player_id){player=text(b.player_id,'Player',80);if(!await db().prepare('SELECT id FROM players WHERE id=?').bind(player).first())throw new APIError('Player tidak ditemukan.');}}
if(b.proof){proof=text(b.proof,'Bukti',100);if(!await db().prepare('SELECT key FROM proofs WHERE key=? AND created_by=?').bind(proof,u.id).first())throw new APIError('Bukti tidak valid.');}}
if(item&&!await db().prepare('SELECT id FROM items WHERE id=?').bind(item).first())throw new APIError('Item tidak ditemukan.');
const ts=now();const q=db();const statements:any[]=[];if(item)statements.push(q.prepare('UPDATE items SET stock=stock+?,updated_at=? WHERE id=?').bind(quantity,ts,item));
statements.push(q.prepare('INSERT INTO transaction_logs(request_id,type,player_id,item_id,amount,quantity,operator,category,description,notes,date,proof,created_by,created_at,reversal_of) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(request,type,player,item,amount,quantity,operator,category,description,notes,day,proof,u.id,ts,original?.id??null));
if(amount!==0)statements.push(q.prepare('INSERT INTO finance_transactions(id,transaction_id,amount,category,created_at,created_by) SELECT ?,id,amount,category,created_at,created_by FROM transaction_logs WHERE request_id=?').bind(uid(),request));
if(type==='Deposit'||(original&&original.type==='Deposit'))statements.push(q.prepare('INSERT INTO deposit_transactions(id,transaction_id,player_id,amount,type,created_at,created_by) SELECT ?,id,player_id,amount,category,created_at,created_by FROM transaction_logs WHERE request_id=?').bind(uid(),request));
if(item)statements.push(q.prepare('INSERT INTO inventory_transactions(id,transaction_id,item_id,quantity,previous_stock,current_stock,created_at,created_by) SELECT ?,t.id,t.item_id,t.quantity,i.stock-t.quantity,i.stock,t.created_at,t.created_by FROM transaction_logs t JOIN items i ON i.id=t.item_id WHERE t.request_id=?').bind(uid(),request));
const sourceType=original?.type||type;const targetChannels=['transactions',...(item?['inventory']:[]),...(sourceType==='Income'?['deposit']:sourceType==='Expense'?['withdraw']:[]),...(sourceType==='Deposit'?['setoran']:[])];for(const ch of targetChannels)statements.push(q.prepare("INSERT INTO notification_logs(id,transaction_id,channel,status,created_at) SELECT ?,id,?,'pending',? FROM transaction_logs WHERE request_id=?").bind(uid(),ch,ts,request));
if(item)statements.push(q.prepare("INSERT INTO notification_logs(id,transaction_id,channel,status,created_at) SELECT ?,t.id,'alerts','pending',? FROM transaction_logs t JOIN items i ON i.id=t.item_id WHERE t.request_id=? AND (i.stock<i.minimum OR i.stock=0)").bind(uid(),ts,request));
try{await q.batch(statements)}catch(e){if(String(e).includes('stock_nonnegative'))throw new APIError('Stok tidak cukup. Transaksi tidak disimpan.');if(String(e).includes('UNIQUE')){const saved=await q.prepare('SELECT id FROM transaction_logs WHERE request_id=? AND created_by=?').bind(request,u.id).first<any>();if(saved)return saved.id;throw new APIError('Transaksi ini sudah dikoreksi.')}throw e;}
const saved=await q.prepare('SELECT id FROM transaction_logs WHERE request_id=?').bind(request).first<any>();try{await deliver(saved.id)}catch(e){console.error('Outbox delivery deferred')}return saved.id;
}
export async function deliver(transactionId?:number){const q=db();const rows=await q.prepare("SELECT n.*,s.env_key,s.enabled FROM notification_logs n LEFT JOIN discord_settings s ON s.channel=n.channel WHERE n.status IN ('pending','failed','unconfigured','sending') AND n.locked_until<? AND (? IS NULL OR n.transaction_id=?) ORDER BY n.created_at LIMIT 20").bind(Date.now(),transactionId??null,transactionId??null).all<any>();await Promise.all(rows.results.map(async n=>{const lock=await q.prepare("UPDATE notification_logs SET locked_until=?,status='sending',attempts=attempts+1 WHERE id=? AND locked_until<? AND status!='sent' RETURNING id").bind(Date.now()+60000,n.id,Date.now()).first();if(!lock)return;const url=runtime()[channels[n.channel]];if(!url||!n.enabled){await q.prepare("UPDATE notification_logs SET status='unconfigured',error=?,locked_until=0 WHERE id=?").bind(!n.enabled?'Channel dinonaktifkan':'Webhook belum dikonfigurasi',n.id).run();return;}
try{const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.hostname!=='discord.com'||!/^\/api\/webhooks\/\d+\/[\w-]+$/.test(parsed.pathname))throw Error('Format webhook Discord tidak valid');const t=await q.prepare('SELECT t.*,p.name player_name,i.name item_name,i.unit item_unit,i.minimum,i.stock,v.previous_stock,v.current_stock FROM transaction_logs t LEFT JOIN players p ON p.id=t.player_id LEFT JOIN items i ON i.id=t.item_id LEFT JOIN inventory_transactions v ON v.transaction_id=t.id WHERE t.id=?').bind(n.transaction_id).first<any>();const cash=await q.prepare('SELECT COALESCE(SUM(amount),0) balance FROM finance_transactions').first<any>();const fields=[{name:'Transaction ID',value:'TRX-'+String(t.id).padStart(6,'0')},{name:'Dicatat oleh',value:t.operator},{name:'Tanggal',value:t.date}];if(t.player_name)fields.push({name:'Player',value:t.player_name});if(t.amount)fields.push({name:'Amount',value:'$'+Number(t.amount).toLocaleString('en-US')},{name:'Saldo saat notifikasi',value:'$'+Number(cash.balance).toLocaleString('en-US')});if(t.item_name)fields.push({name:'Item',value:t.item_name},{name:'Quantity',value:String(t.quantity)+' '+t.item_unit},{name:'Stock',value:`${t.previous_stock} → ${t.current_stock}`});fields.push({name:'Keterangan',value:t.description});const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'DCMC',allowed_mentions:{parse:[]},embeds:[{title:n.channel==='alerts'?'LOW STOCK ALERT':n.channel==='setoran'?(t.item_id?'SETORAN ITEM':'SETORAN UANG'):n.channel==='deposit'?'DEPOSIT ORGANISASI':n.channel==='withdraw'?'WITHDRAW ORGANISASI':t.type.toUpperCase(),color:15615308,fields,timestamp:t.created_at}]}),signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('Discord HTTP '+response.status);await q.prepare("UPDATE notification_logs SET status='sent',error=NULL,sent_at=?,locked_until=0 WHERE id=?").bind(now(),n.id).run();}catch(e){await q.prepare("UPDATE notification_logs SET status='failed',error=?,locked_until=0 WHERE id=?").bind(e instanceof Error&&/^Discord HTTP|^Format webhook/.test(e.message)?e.message:'Pengiriman Discord gagal atau timeout',n.id).run();}}));}
